@apiurl = localhost:8000
@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvYW5hQGdtYWlsLmNvbSIsImV4cCI6MTcwNTYwMjA1NSwiaWQiOjMsIm5hbWUiOiJqb2FuYSJ9.yu4nF9_CBrZWAKyG3UWroA1lgi-J2WMFL0KCMprryKA

### GetUserData
GET /u/me HTTP/1.1
Host: {{apiurl}}
Authorization: Bearer {{access_token}}

### UpdateUserData
PATCH /u/me HTTP/1.1
Host: {{apiurl}}
Content-Type: application/json
Authorization: Bearer {{access_token}}
Content-Length: 109

{
    "name": "sidney",
    "email": "sidney@gmail.com",
    "username": "sidney",
    "born_date": "2022-09-04"
}

### DeactivateUserByID
DELETE /u/2 HTTP/1.1
Host: {{apiurl}}
Authorization: Bearer 

### CreateUserPost
POST /u/me/post HTTP/1.1
Host: {{apiurl}}
Content-Type: application/json
Authorization: Bearer {{access_token}}
Content-Length: 114

{
    "title": "priv2",
    "content": "dmFpIHRyYWJhaWEgIQ==",
    "category": "programming",
    "is_public": 1
}

### ListUserPosts
GET /u/me/posts HTTP/1.1
Host: {{apiurl}}
Authorization: Bearer {{access_token}}

### GetUserPostsContent
GET /u/me/posts/content HTTP/1.1
Host: {{apiurl}}
Authorization: Bearer {{access_token}}