### CreateNewUser
POST /u HTTP/1.1
Host: localhost:8000
Content-Type: application/json
Content-Length: 138

{
    "name": "mary",
    "email": "mary@gmail.com",
    "username": "mary",
    "born_date": "2022-09-04",
    "password": "pass@1234"
}

### GetAllPublicPosts
GET /u/anonymous/posts HTTP/1.1
Host: localhost:8000

### GetUserByIDorUsername
GET /u/mary HTTP/1.1
Host: localhost:8000

### CreateAnonymousPost
POST /u/anonymous/post HTTP/1.1
Host: localhost:8000
Content-Type: application/json
Content-Length: 544

{
    "title": "My Public Post",
    "content": "dmFpIHRyYWJhaWEgIQ==",
    "category": "programming"
}

### GetPublicPosByIDorUrl
GET /u/anonymous/qkFqqeqBI0 HTTP/1.1
Host: localhost:8000