@apiurl = localhost:8000

### Login
POST /login HTTP/1.1
Host: {{apiurl}}
Content-Type: application/json
Content-Length: 64

{
    "email": "joana@gmail.com",
    "password": "1234"
}

@apiurl = localhost:8000

####################################################################

### GetAllUsers
GET /u/all HTTP/1.1
Host: {{apiurl}}
owner: apolzek

### GetAllActiveUsers
GET /u HTTP/1.1
Host: {{apiurl}}
owner: apolzek

### GetAllActiveUsersPaginate
GET /u/paginate?page=1&perPage=12 HTTP/1.1
Host: {{apiurl}}
owner: apolzek


####################################################################

@apiurl = localhost:8000
@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvYW5hQGdtYWlsLmNvbSIsImV4cCI6MTcwNTYwMjA1NSwiaWQiOjMsIm5hbWUiOiJqb2FuYSJ9.yu4nF9_CBrZWAKyG3UWroA1lgi-J2WMFL0KCMprryKA

### GetUserData
GET /u/me HTTP/1.1
Host: {{apiurl}}
Authorization: Bearer {{access_token}}

### UpdateUserData
PATCH /u/me HTTP/1.1
Host: {{apiurl}}
Content-Type: application/json
Authorization: Bearer {{access_token}}
Content-Length: 109

{
    "name": "sidney",
    "email": "sidney@gmail.com",
    "username": "sidney",
    "born_date": "2022-09-04"
}

### DeactivateUserByID
DELETE /u/2 HTTP/1.1
Host: {{apiurl}}
Authorization: Bearer 

### CreateUserPost
POST /u/me/post HTTP/1.1
Host: {{apiurl}}
Content-Type: application/json
Authorization: Bearer {{access_token}}
Content-Length: 114

{
    "title": "priv2",
    "content": "dmFpIHRyYWJhaWEgIQ==",
    "category": "programming",
    "is_public": 1
}

### ListUserPosts
GET /u/me/posts HTTP/1.1
Host: {{apiurl}}
Authorization: Bearer {{access_token}}

### GetUserPostsContent
GET /u/me/posts/content HTTP/1.1
Host: {{apiurl}}
Authorization: Bearer {{access_token}}

####################################################################

### CreateNewUser
POST /u HTTP/1.1
Host: localhost:8000
Content-Type: application/json
Content-Length: 138

{
    "name": "mary",
    "email": "mary@gmail.com",
    "username": "mary",
    "born_date": "2022-09-04",
    "password": "pass@1234"
}

### GetAllPublicPosts
GET /u/anonymous/posts HTTP/1.1
Host: localhost:8000

### GetUserByIDorUsername
GET /u/mary HTTP/1.1
Host: localhost:8000

### CreateAnonymousPost
POST /u/anonymous/post HTTP/1.1
Host: localhost:8000
Content-Type: application/json
Content-Length: 544

{
    "title": "My Public Post",
    "content": "dmFpIHRyYWJhaWEgIQ==",
    "category": "programming"
}

### GetPublicPosByIDorUrl
GET /u/anonymous/qkFqqeqBI0 HTTP/1.1
Host: localhost:8000