POST /u HTTP/1.1
Host: localhost:8000
Content-Type: application/json
Content-Length: 139

{
    "name": "joana",
    "email": "joana@gmail.com",
    "username": "joana",
    "born_date": "2022-09-04",
    "password": "1234"
}
