version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'go_gin_gonic'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '1234'
      MYSQL_ROOT_PASSWORD: 'root@1234'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql_db_volume:/var/lib/mysql
volumes:
  mysql_db_volume: